// SPDX-License-Identifier: GPL-2.0-or-later
#import "SaveStore.h"
#import <CommonCrypto/CommonDigest.h>
static NSString *Hash(NSData *d){unsigned char h[CC_SHA256_DIGEST_LENGTH];CC_SHA256(d.bytes,(CC_LONG)d.length,h);NSMutableString *s=[NSMutableString new];for(int i=0;i<CC_SHA256_DIGEST_LENGTH;i++)[s appendFormat:@"%02x",h[i]];return s;}
@implementation SaveStore
- (NSString *)directory{NSString *p=[NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES).firstObject stringByAppendingPathComponent:@"NativeSaves"];[NSFileManager.defaultManager createDirectoryAtPath:p withIntermediateDirectories:YES attributes:nil error:nil];return p;}
- (BOOL)save:(NSData *)state image:(UIImage *)image slot:(NSInteger)slot snapshot:(BOOL)snapshot{
 if(!state.length)return NO;NSString *name=[NSString stringWithFormat:@"slot-%ld.state",(long)slot],*dir=self.directory;
 BOOL ok=[state writeToFile:[dir stringByAppendingPathComponent:@"latest.state"] options:NSDataWritingAtomic error:nil];if(!ok)return NO;
 [state writeToFile:[dir stringByAppendingPathComponent:name] options:NSDataWritingAtomic error:nil];
 NSMutableArray *names=[NSMutableArray arrayWithArray:@[@"latest.state",name]];
 if(snapshot){NSString *history=[NSString stringWithFormat:@"%.0f.state",NSDate.date.timeIntervalSince1970*1000];[state writeToFile:[dir stringByAppendingPathComponent:history] options:NSDataWritingAtomic error:nil];[names addObject:history];}
 for(NSString *n in names){NSDictionary *meta=@{@"date":NSDate.date,@"source":snapshot?@"يدوي":@"تلقائي",@"sha256":Hash(state)};[meta writeToFile:[[dir stringByAppendingPathComponent:n] stringByAppendingString:@".plist"] atomically:YES];if(image)[UIImagePNGRepresentation(image) writeToFile:[[dir stringByAppendingPathComponent:n] stringByAppendingString:@".png"] atomically:YES];}
 NSMutableArray *history=[NSMutableArray new];for(NSString *n in [NSFileManager.defaultManager contentsOfDirectoryAtPath:dir error:nil])if([n.pathExtension isEqual:@"state"]&&[n characterAtIndex:0]>='0'&&[n characterAtIndex:0]<='9')[history addObject:n];[history sortUsingSelector:@selector(compare:)];while(history.count>6){[self remove:history.firstObject];[history removeObjectAtIndex:0];}return YES;
}
- (NSArray *)records{NSMutableArray *out=[NSMutableArray new];NSString *dir=self.directory;for(NSString *n in [NSFileManager.defaultManager contentsOfDirectoryAtPath:dir error:nil])if([n.pathExtension isEqual:@"state"]){NSString *path=[dir stringByAppendingPathComponent:n];NSDictionary *m=[NSDictionary dictionaryWithContentsOfFile:[path stringByAppendingString:@".plist"]];NSDate *date=m[@"date"]?:[NSFileManager.defaultManager attributesOfItemAtPath:path error:nil][NSFileModificationDate];NSString *title=[n isEqual:@"latest.state"]?@"آخر حفظ":[n hasPrefix:@"slot-"]?[NSString stringWithFormat:@"خانة %@",[[n substringFromIndex:5] stringByDeletingPathExtension]]:@"حفظ سابق";[out addObject:@{@"name":n,@"title":title,@"date":date?:NSDate.date,@"source":m[@"source"]?:@"يدوي",@"image":[path stringByAppendingString:@".png"]}];}return [out sortedArrayUsingComparator:^NSComparisonResult(NSDictionary *a,NSDictionary *b){if([a[@"name"] isEqual:@"latest.state"])return NSOrderedAscending;if([b[@"name"] isEqual:@"latest.state"])return NSOrderedDescending;return [b[@"date"] compare:a[@"date"]];}];}
- (NSData *)state:(NSString *)name{if(![name isEqual:name.lastPathComponent]||![name.pathExtension isEqual:@"state"])return nil;NSString *p=[self.directory stringByAppendingPathComponent:name];NSData *d=[NSData dataWithContentsOfFile:p];NSDictionary *m=[NSDictionary dictionaryWithContentsOfFile:[p stringByAppendingString:@".plist"]];if(m[@"sha256"]&&![m[@"sha256"] isEqual:Hash(d)])return nil;return d;}
- (void)remove:(NSString *)name{if(![name isEqual:name.lastPathComponent])return;for(NSString *suffix in @[@"",@".plist",@".png"])[NSFileManager.defaultManager removeItemAtPath:[[self.directory stringByAppendingPathComponent:name] stringByAppendingString:suffix] error:nil];}
- (NSURL *)exportRecord:(NSString *)name{NSData *d=[self state:name];if(!d)return nil;NSDictionary *p=@{@"format":@"V61D-FCEUmm-state-v1",@"rom":@"f61548fdf1670cffefcc4f0b7bdcdd9eaba0c226e3b74f8666071496988248de",@"state":d,@"sha256":Hash(d)};NSData *blob=[NSPropertyListSerialization dataWithPropertyList:p format:NSPropertyListBinaryFormat_v1_0 options:0 error:nil];NSURL *url=[NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:[name.stringByDeletingPathExtension stringByAppendingPathExtension:@"vsave"]]];return [blob writeToURL:url options:NSDataWritingAtomic error:nil]?url:nil;}
- (BOOL)importURL:(NSURL *)url expectedSize:(NSUInteger)size{NSData *d=[NSData dataWithContentsOfURL:url options:NSDataReadingMappedIfSafe error:nil];if(d.length>4*1024*1024)return NO;NSDictionary *p=[NSPropertyListSerialization propertyListWithData:d options:NSPropertyListImmutable format:nil error:nil];if(![p isKindOfClass:NSDictionary.class]||![p[@"format"] isEqual:@"V61D-FCEUmm-state-v1"]||![p[@"rom"] isEqual:@"f61548fdf1670cffefcc4f0b7bdcdd9eaba0c226e3b74f8666071496988248de"]||![p[@"state"] isKindOfClass:NSData.class])return NO;NSData *state=p[@"state"];if(state.length!=size||![Hash(state) isEqual:p[@"sha256"]])return NO;return [self save:state image:nil slot:1 snapshot:YES];}
@end
